blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('detail/<int:pid>/', blog_single, name='single'),
    path('category/<str:category_name>/', blog_category, name='category'),
    path('author/<str:author_username>/', blog_view, name='author'),
    path('tag/<str:tag_name>/', blog_view, name='tag'),
    path('search/', blog_search, name='search'),
    path('<int:pid>/', blog_view, name='blog_detail'),

]

website/urls.py
from django.urls import path
from .views import *

app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('contact/', contact_view, name='contact'),
    path('thanks/', thanks_view, name='thanks'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField('Category')
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField(default=timezone.now)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-status']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid': self.id})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    massage = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    approach = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from blog.models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['name', 'email', 'massage']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from blog.models import Post, Comment
from blog.forms import CommentForm
from django.contrib import messages
from django.http import HttpResponseRedirect


def get_queryset():
    return Post.objects.filter(status=1, published_date__lte=timezone.now())


def blog_view(request, **kwargs):
    # دریافت همه پست‌ها و مرتب‌سازی بر اساس تاریخ انتشار
    posts = Post.objects.all().order_by('-published_date')

    # فیلتر کردن پست‌ها بر اساس دسته‌بندی، نویسنده یا برچسب
    if 'category_name' in kwargs:
        posts = posts.filter(category__name=kwargs['category_name'])
    if 'author_username' in kwargs:
        posts = posts.filter(author__username=kwargs['author_username'])
    if 'tag_name' in kwargs:
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])

    # تنظیم صفحه‌بندی، نمایش ۳ پست در هر صفحه
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page')

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        # اگر شماره صفحه عدد صحیح نیست، اولین صفحه را نمایش بده
        page_obj = paginator.page(1)
    except EmptyPage:
        # اگر شماره صفحه خارج از محدوده است، آخرین صفحه را نمایش بده
        page_obj = paginator.page(paginator.num_pages)

    # آماده‌سازی کانتکست برای قالب
    context = {'posts': page_obj.object_list, 'page_obj': page_obj}

    # رندر کردن قالب لیست وبلاگ با کانتکست
    return render(request, 'blog/blog-list.html', context)


def blog_single(request, pid):
    post = get_object_or_404(Post, pk=pid)

    if post.login_require and not request.user.is_authenticated:
        return redirect('accounts:login')

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            messages.success(request, 'پیام شما با موفقیت ثبت شد')
            return HttpResponseRedirect(request.path_info)
        else:
            # چاپ خطاهای فرم برای دیباگ
            print(form.errors)
            messages.error(request, 'خطایی رخ داده است')
            return HttpResponseRedirect(request.path_info)
    else:
        form = CommentForm()
        post.counted_views += 1
        post.save()

        next_post = Post.objects.filter(
            status=1, published_date__gt=post.published_date).order_by('published_date').first()
        prev_post = Post.objects.filter(
            status=1, published_date__lt=post.published_date).order_by('-published_date').first()

        comments = Comment.objects.filter(post=post.id, approach=True)
        context = {
            'post': post,
            'next_post': next_post,
            'prev_post': prev_post,
            'comments': comments,
            'form': form
        }
        return render(request, 'blog/blog-single.html', context)


def blog_category(request, category_name):
    posts = get_queryset().filter(category__name=category_name)

    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page')
    try:
        page_posts = paginator.page(page_number)
    except PageNotAnInteger:
        page_posts = paginator.page(1)
    except EmptyPage:
        page_posts = paginator.page(paginator.num_pages)

    context = {'posts': page_posts}
    return render(request, 'blog/blog-list.html', context)


def blog_search(request):
    posts = get_queryset()
    if 's' in request.GET:
        query = request.GET['s']
        posts = posts.filter(content__icontains=query)

    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page')
    try:
        page_posts = paginator.page(page_number)
    except PageNotAnInteger:
        page_posts = paginator.page(1)
    except EmptyPage:
        page_posts = paginator.page(paginator.num_pages)

    context = {'posts': page_posts}
    return render(request, 'blog/blog-list.html', context)


def blog_detail(request, pid):
    post = get_object_or_404(get_queryset(), pk=pid)
    return render(request, 'blog/blog_detail.html', {'post': post})

templates/blog/blog-list.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block content %}
  {% load jformat %}
  <html lang="fa" dir="rtl">
    <body>
      <!-- Preloader -->
      <div id="preloader">
        <div class="loading-area">
          <div class="circle"></div>
        </div>
        <div class="left-side"></div>
        <div class="right-side"></div>
      </div>

      <div class="header-mobile">
        <a class="header-toggle"><i class="fas fa-bars"></i></a>
        <h2>مهیار حیدری</h2>
      </div>

      <!-- Blog Page -->
      <div class="blog-list" data-simplebar>
        <div class="blog-head">
          <h2>بلاگ</h2>
          <ul class="blog-breadcrumb">
            <li>
              <a href="{% url 'website:index' %}">خانه</a>
            </li>
            <li>بلاگ</li>
          </ul>
        </div>
        <div class="row blog-list-container">
          <div class="col-md-10 offset-md-1">
            <div class="row">
              <div class="col-md-8">
                <!-- Blog Post -->
                {% for post in posts %}
                  <div class="blog-post">
                    <div class="content">
                      <div class="thumbnail">
                        <a href=""><img src="{{ post.image.url }}" alt="{{ post.title }}" /></a>
                      </div>
                      <div class="detalis">
                        <ul class="meta">
                          {% for category in post.category.all %}
                            <li>
                              <i class="fa fa-list"></i><a href="{% url 'blog:category' category_name=category.name %}">{{ category.name }}</a>{% if not forloop.last %}, {% endif %}
                            </li>
                          {% endfor %}
                          <li>
                            <i class="fa fa-calendar"></i>{{ post.published_date|jformat:'%d %m %Y' }}
                          </li>
                          <li>
                            <i class="icon fa fa-user"></i><a href="{% url 'blog:author' author_username=post.author %}">{{ post.author.username }}</a>
                          </li>
                          <li>
                            <i class="fa fa-comments"></i><a>{% comments_count post.id %}</a>
                          </li>
                        </ul>
                        <h4><a href="{% url 'blog:single' post.id %}">{{ post.title }}</a></h4>
                        <div class="text">{{ post.content|truncatewords:15|safe }}</div>
                        <a href="{% url 'blog:single' post.id %}" class="btn-st">مشاهده بیشتر</a>
                      </div>
                    </div>
                  </div>
                {% endfor %}

                <!-- Pagination Blog -->
                {% if page_obj.paginator.num_pages > 1 %}
                  <ul class="pagination">
                    <li class="page-item">
                      <a href="?page=1{% if category_name %}{{ category_name }}{% endif %}{% if author_username %}{{ author_username }}{% endif %}" aria-label="First"><span aria-hidden="true"><span class="fa fa-angle-right"></span></span></a>
                    </li>
                    <li class="page-item {% if page_obj.number == 1 %}{% endif %}">
                      <a href="?page=1{% if category_name %}{{ category_name }}{% endif %}{% if author_username %}{{ author_username }}{% endif %}">1</a>
                    </li>
                    {% for num in page_obj.paginator.page_range %}
                      {% if num > 1 and num < page_obj.paginator.num_pages %}
                        <li class="page-item {% if num == page_obj.number %}{% endif %}">
                          <a href="?page={{ num }}{% if category_name %}{{ category_name }}{% endif %}{% if author_username %}{{ author_username }}{% endif %}">{{ num }}</a>
                        </li>
                      {% endif %}
                    {% endfor %}
                    <li class="page-item {% if page_obj.number == page_obj.paginator.num_pages %}{% endif %}">
                      <a href="?page={{ page_obj.paginator.num_pages }}{% if category_name %}{{ category_name }}{% endif %}{% if author_username %}{{ author_username }}{% endif %}">{{ page_obj.paginator.num_pages }}</a>
                    </li>
                    <li class="page-item">
                      <a href="?page={{ page_obj.paginator.num_pages }}{% if category_name %}{{ category_name }}{% endif %}{% if author_username %}{{ author_username }}{% endif %}" aria-label="Last"><span aria-hidden="true"><span class="fa fa-angle-left"></span></span></a>
                    </li>
                  </ul>
                {% endif %}
              </div>

              <div class="col-md-4">
                <div class="side-left">
                  <!-- Search -->
                  {% search %}
                  <!-- Categories -->
                  <div class="categories">
                    <h4>دسته‌بندی ها</h4>
                    <ul>
                      {% postcategories %}
                    </ul>
                  </div>

                  <!-- Recent News -->
                  <div class="news">
                    <h4>اخرین مطالب</h4>
                    <ul>
                      {% latestposts %}
                    </ul>
                  </div>

                  <!-- Gallery -->
                  <div class="gallery">
                    <h4>گالری</h4>
                    <div class="row">
                      {% for post in posts %}
                        <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                          <div class="gallery-item">
                            <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid gallery-image" />
                          </div>
                        </div>
                      {% endfor %}
                    </div>
                  </div>

                  <!--                     Archives
                  <div class="archives">
                    <h4>بایگانی</h4>
                    <ul>
                      <li>
                        <a href="#">اسفند 1398</a>
                      </li>
                      <li>
                        <a href="#">بهمن 1398</a>
                      </li>
                      <li>
                        <a href="#">دی 1398</a>
                      </li>
                    </ul>
                  </div>
                                       -->

                  <!-- Tags -->
                  <div class="tags">
                    <h4>برچسب ها</h4>
                    <ul>
                      <li>
                        {% postcategories1 %}
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </body>
  </html>
{% endblock %}

templates/blog/blog-popular-posts.html
{% load static %}
{% load humanize %}
{% load jformat %}
<div class="single-sidebar-widget popular-post-widget">
  <div class="popular-post-list">
    {% for post in posts %}
      <div class="single-post-list d-flex flex-row align-items-center">
        <div class="thumb">
          <img class="img-fluid" src="{{ post.image.url }}" alt="" />
        </div>
        <div class="details">
          <a href="{% url 'blog:single' post.id %}"><h6>{{ post.title }}</h6></a>
          <p>{{ post.published_date|jformat:'%d %m %Y' }}</p>
          <p>{{ post.published_date|naturaltime }}</p>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

templates/blog/blog-post-categories.html
<div class="single-sidebar-widget post-category-widget">
  <ul class="cat-list">
    {% for name, count in categories.items %}
      <li>
        <a href="{% url 'blog:category' category_name=name %}" class="d-flex justify-content-between">
          <p>{{ name }}</p>
          <p>{{ count }}</p>
        </a>
      </li>
    {% endfor %}
  </ul>
</div>

templates/blog/blog-post-tag.html
<div class="single-sidebar-widget post-category-widget">
  <ul class="cat-list">
    {% for name, count in categories.items %}
      <li>
        <a href="{% url 'blog:category' category_name=name %}" class="d-flex justify-content-between"><p>{{ name }}</p></a>
      </li>
    {% endfor %}
  </ul>
</div>

templates/blog/blog-search.html
<form class="search" action="{% url 'blog:search' %}" method="get">
  <div class="input-group">
    <div class="input-group-text">
      <i class="fas fa-search"></i>
    </div>
    <input type="text" class="form-control" placeholder="جستجو ..." name="s" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" />
  </div>
</form>

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load jformat %}
  <!DOCTYPE html>
  <html lang="fa" dir="rtl">
    <head>
      <!-- Blog Page -->
      <div class="blog-page" data-simplebar>
        <nav class="blog-nav">          
          {% if prev_post %}
              <a href="{% url 'blog:single' pid=prev_post.id %}" data-tooltip="قبلی" data-position="left"><i class="fas fa-long-arrow-alt-right"></i></a>
          {% endif %}
          <a href="{% url 'blog:index' %}"><i class="fas fa-bars"></i></a>
          {% if next_post %}
              <a href="{% url 'blog:single' pid=next_post.id %}" data-tooltip="بعدی" data-position="right"><i class="fas fa-long-arrow-alt-left"></i></a>
          {% endif %}       
        </nav>
        <div class="blog-image">
          <img src="{% static 'img/blog/blog-page-img.jpg' %}" alt="" />
        </div>
        <div class="row blog-container">
          <div class="col-md-10 offset-md-1">
            <!-- Heading -->
            <div class="blog-heading pt-70 pb-100">
              <a><img src="{{ post.image.url }}" alt="{{ post.title }}" /></a>
              <h2>{{ post.title }}</h2>
              <span>
                {% for category in post.category.all %}
                <i class="fa fa-list"></i><a href="{% url 'blog:category' category_name=category.name %}">{{ category.name }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
              </span>
              <span><i class="fas fa-comment"></i><a href="#">5 دیدگاه</a></span>
              <span><i class="fas fa-calendar-alt"></i>{{ post.published_date|jformat:'%d %m %Y' }}</span>
              <span><i class="fas fa-eye"></i>بازدید {{ post.counted_views }}</span>
            </div>

            <!-- Content -->
            <div class="blog-content">
              <p class="excert">{{ post.content|truncatewords:30|safe }}</p>
              
                {% include 'blog/blog-writer.html' %}
      
              <p class="excert">{{ post.content|safe }}</p>
            </div>

            <!-- Comments -->
            <div class="blog-comments mt-100 mb-100">
              <div class="header-box mb-50">
                <h3>دیدگاه‌ها</h3>
                  {% for comment in comments %}
                  <div class="comment-list">
                    <div class="single-comment justify-content-between d-flex">
                      <div class="user justify-content-between d-flex">
                        <div class="thumb">
                          <img src="{% static 'img/blog/authors/author-1.png' %}" alt="" />
                        </div>
                        <div class="desc">
                          <h5><a href="#">{{ comment.name }}</a></h5>
                          <p class="date">{{ comment.created_date|jformat:'%d %m %Y' }}</p>
                          <p class="comment">{{ comment.massage }}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  {% empty %}
                    <p class="comment">هیچ نظری ثبت نشده...</p>
                  {% endfor %}
              </div>
            </div>

            <!-- Blog Form -->
            <div class="header-box mb-50">
              <h3>دیدگاه خود را بیان کنید</h3>
            </div>
            <div class="contact-form mb-100">
              {% if messages %}
                  <div class="messages">
                      {% for message in messages %}
                          <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                              {{ message }}
                          </div>
                      {% endfor %}
                  </div>
              {% endif %}
            <form method="post" action="{% url 'blog:single' post.pk %}">
              {% csrf_token %}
                <input type="hidden" name="post" value="{{ post.pk }}" />
                  {% if request.user.is_authenticated %}
                      <input type="hidden" name="name" value="{{ request.user.first_name }}" />
                      <input type="hidden" name="email" value="{{ request.user.email }}" />
                  {% else %}
                      <div class="row">
                          <div class="col-lg-6 col-sm-12">
                              <input type="text" name="name" class="form-control" placeholder="نام *" onfocus="this.placeholder = ''" onblur="this.placeholder = 'نام *'" required />
                          </div>
                          <div class="col-lg-6 col-sm-12 mt-3 mt-lg-0">
                              <input type="email" name="email" class="form-control" placeholder="ایمیل *" dir="ltr" onfocus="this.placeholder = ''" onblur="this.placeholder = 'ایمیل *'" required />
                          </div>
                      </div>
                  {% endif %}
                  <div class="col-lg-12 col-sm-12">
                    <textarea class="form-control" name="massage" placeholder="پیام شما" required></textarea>
                  </div>
                  <div class="col-lg-12 col-sm-12 text-center">
                      <button type="submit" class="btn-st">ارسال پیام</button>
                  </div>
            </form>
          </div>
      </div>
    </body>
  </html>
{% endblock %}

templates/blog/blog-tags.html
<div class="single-sidebar-widget tag-cloud-widget">
  <h4 class="tagcloud-title">برچسب‌ها</h4>
  <ul>
    {% if not posts %}
      {# اگر هیچ تگی وجود نداشت، تمام تگ‌ها را نمایش بده #}
      {% for tag in all_tags %}
        <li>
          <a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a>
        </li>
      {% endfor %}
    {% else %}
      {# اگر تگ‌ها وجود داشتند، آنها را نمایش بده #}
      {% for post in posts %}
        <li>
          <a href="{% url 'blog:tag' tag_name=post.name %}">{{ post.name }}</a>
        </li>
      {% endfor %}
    {% endif %}
  </ul>
</div>

templates/blog/blog-writer.html
{% load static %}
<p>
  <blockquote>
    نویسنده
    <span>
      <img src="{% static 'img/blog/authors/author-1.png' %}" alt="" /><a href="{% url 'blog:author' author_username=post.author %}">{{ post.author.username }}
      <a href="#"><i class="fab fa-youtube"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </span>
  </blockquote>
</p>

templates/blog/blog_detail.html
<section class="recent-blog-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-60 col-lg-9">
        <div class="title text-center">
          <h1 class="mb-10">Latest from Our Blog</h1>
          <p>With the exception of Nietzsche, no other madman has contributed so much to human sanity as has.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="active-recent-blog-carusel">
        {% for post in posts %}
          <div class="single-recent-blog-post item">
            <div class="thumb">
              <img class="img-fluid" src="{{ post.image.url }}" alt="" />
            </div>
            <div class="details">
              <div class="tags">
                <ul>
                  {% for category in post.category.all %}
                    <li>
                      <a href="{% url 'blog:category' category_name=category.name %}">{{ category.name }}</a>
                    </li>
                  {% endfor %}
                </ul>
              </div>
              <a href="{% url 'blog:single' post.id %}"><h4 class="title">{{ post.title }}</h4></a>
              <p>{{ post.content|truncatewords:15 }}</p>
              <h6 class="date">{{ post.published_date|date:'d M Y' }}</h6>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>